# Generated by Django 5.2.9 on 2025-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ammonia', models.FloatField()),
                ('nitrites', models.FloatField()),
            ],
        ),
    ]
