# Generated by Django 5.2.9 on 2025-12-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ammonia', models.FloatField()),
                ('nitrites', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_liters', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('water_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='parameters.tank'),
        ),
    ]
