# Generated by Django 5.2.9 on 2025-12-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_measurement_tank_delete_measurements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='nitrates',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
